### ISSUE TITLE
v20 Issues

### ISSUE THREAD

**Issue by ericorosel** [sparkfun/GPS_Shield#2]
-Need PROD_ID for batt. clip (according to the BOM it is CONN-08044)

-This may not be an issue at all, but when I match up the Redboard ISP header and the GPS Shield ISP header they seem to be slightly off. 

that's it!

**Comment by ericorosel** [comment]
sorry, that's BATT-08044

**Comment by jimblom** [comment]
Battery's all taken care of.

The ISP header may actually be slightly off position on the Redboard. The GPS shield matches up with an Arduino Uno and a SAMD21 Dev Breakout. Either way, with a little give in the headers it's close enough.

**Comment by ericorosel** [comment]
Sounds good, thanks!
